### ISSUE TITLE
Unsure about completion

### ISSUE THREAD

**Issue by zefreak** [jayree/sfdx-autocomplete-plugin#14]
Apologies if this is the wrong place to ask, but I installed the plugin and am getting initial tab completion (when i type sfdx force and tab) however if I start tying (for example force:org) there is no more completion. Is that supported?

Thanks for putting this together

**Comment by jayree** [comment]
@zefreak are you using bash or zsh? You need to press 'TAB TAB' in bash and 'TAB' in zsh to see the list of available commands or flags.

Please confirm, that you have performed the following steps:

```sh-session
$ sfdx autocomplete
```

For bash (Please note, on MAC the terminal starts as a login shell):
```sh-session
1) Add the autocomplete env var to your bash profile and source it
$ printf "$(sfdx autocomplete:script bash)" >> ~/.bashrc; source ~/.bashrc

NOTE: If your terminal starts as a login shell 
you may need to print the init script into ~/.bash_profile or ~/.profile.

2) Test it out, e.g.:
$ sfdx <TAB><TAB>                 # Command completion
$ sfdx command --<TAB><TAB>       # Flag completion
```

For zsh:
```sh-session
1) Add the autocomplete env var to your zsh profile and source it
$ printf "$(sfdx autocomplete:script zsh)" >> ~/.zshrc; source ~/.zshrc

NOTE: After sourcing, you can run `$ compaudit -D` to ensure no permissions conflicts are present

2) Test it out, e.g.:
$ sfdx <TAB>                 # Command completion
$ sfdx command --<TAB>       # Flag completion
```

Then in both shells this:
```
$ sfdx <SPACE> f <TAB> o <TAB> o <TAB>
```
should be completed to:
```
$ sfdx force:org:open
```

**Comment by zefreak** [comment]
Thanks for the response -

I am using bash. When I type sfdx f <TAB> it autocompletes to force: but when I press o <TAB> I get the following error:
Warning: autocomplete:options is not a sfdx command. Did you mean plugins?

This is different behavior than it was before so I'm getting closer

**Comment by jayree** [comment]
please update to: 

> sfdx-cli/7.1.4

and test the current beta: 
`sfdx plugins:install jayree/sfdx-autocomplete-plugin#oclif`

there will be a built-in autocompletion in the near future [Salesforce CLI v45 Release Notes](https://developer.salesforce.com/media/salesforce-cli/releasenotes.html)
