### ISSUE TITLE
Syntax error for named exports

### ISSUE THREAD

**Issue by osieckiAdam** [jayree/sfdx-autocomplete-plugin#304]
Hey, I just installed the latest version (2.9.9) and when I want to use any command, e.g. 
```
sfdx autocmplt
```
I'm getting following error:

SyntaxError: Named export 'StateAggregator' not found. The requested module '@salesforce/core' is a CommonJS module, which may not support all module.exports as named exports.
    CommonJS modules can always be imported via the default export, for example using:

    import pkg from '@salesforce/core';
    const { StateAggregator } = pkg;

**Comment by jayree** [comment]
@osieckiAdam sorry I missed this one. Do you still see this issue?
